# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHbvkCnN-yUTDzHcUuiTCWpe9q0tNU51
"""

#Question 1

The jumbled word : OBANWRI
The right option : (B) RAINBOW

#Question 2

str = input()
print(str.upper())

#Question 3 
#Printing Profit

cp = input()
sp = input()
if(cp<sp):
  print("Profit")
elif(cp>sp):
  print("Loss")
else:
  print("Neither")

#Question 3
#Printing Loss

cp = input()
sp = input()
if(cp<sp):
  print("Profit")
elif(cp>sp):
  print("Loss")
else:
  print("Neither")

#Question 3
#Printing Neither

cp = input()
sp = input()
if(cp<sp):
  print("Profit")
elif(cp>sp):
  print("Loss")
else:
  print("Neither")

#Question 4
euro = input()
euro = int(euro)
indian_rupee = euro * 80
print(indian_rupee)